REG COPY HKLM\HARDWARE\ACPI\DSDT\VBOX__ HKLM\HARDWARE\ACPI\DSDT\NOBOX__ /s /f
REG DELETE HKLM\HARDWARE\ACPI\DSDT\VBOX__ /f
REG DELETE HKLM\HARDWARE\DESCRIPTION\System /v SystemBiosVersion /f
REG ADD HKLM\HARDWARE\DESCRIPTION\System /v SystemBiosVersion /t REG_MULTI_SZ /d "NOBOX   - 1" /f
REG DELETE HKLM\HARDWARE\DESCRIPTION\System /v VideoBiosVersion /f
REG ADD HKLM\HARDWARE\DESCRIPTION\System /v VideoBiosVersion /t REG_MULTI_SZ /f